project:
  type: website
  output-dir: _site

website:
  title: "ML – Missing Semester CUET"
  search: true
  navbar:
    background: transparent
    left:
      - text: "Home"
        href: index.md
    right:
      - text: "Software Dev"
        href: "https://missingsemestercuet.github.io/SD/"
      - text: "Cybersecurity"
        href: "https://missingsemestercuet.github.io/Cyber/"
      - icon: github
        href: "https://github.com/MissingSemesterCUET/ML"
  page-footer:
    left: "Missing Semester CUET"
    center: "© 2026"
    right: 
      - icon: github
        href: "https://github.com/MissingSemesterCUET/ML"

execute:
  enabled: false

format:
  html:
    theme: none
    css: styles.css
    include-before-body: navbar.html
    html-math-method: mathjax
    highlight-style: atom-one-dark
    toc: true
    code-tools: true
    code-copy: true
    embed-resources: false

notebook-links: true
